library/urls.py
from django.contrib import admin
from django.urls import path
from .import views 

app_name= 'library'

urlpatterns = [
   path("", views.index, name="index"),
   path("search_student", views.search_student, name="search_student"),
   path("student", views.student, name="student"),
   
   path("books", views.books, name= "books"),
   path("edit_add_books/", views.edit_add_books, name="edit_add_books"),
   path("edit_add_books_view/", views.edit_add_books_view, name='edit_add_books_view'),
   path("edit_book_borrowed",views.edit_book_borrowed, name="edit_book_borrowed"),
   path("edit_book_borrowed_view",views.edit_book_borrowed_view, name="edit_book_borrowed_view"),
   path("add_books", views.add_books, name= "add_books"),
   path("add_student", views.add_student, name="add_student"),
   path("lib_staff", views.lib_staff, name="lib_staff"),
   path("book_borrowed_view", views.book_borrowed_view, name="book_borrowed_view"),
   path("book_borrowed", views.book_borrowed, name="book_borrowed"),
   path("book_details/<int:id>/", views.book_details, name= "book_details_name"),
   path("all_books", views.all_books, name= "all_books"),
   path("author", views.author, name= "author"),
   path("author_profile", views.author_profile, name= "author_profile"),
   path("form", views.form, name= "form"),
   path("login", views.login_view, name="login"),
   path("register", views.register, name="register"),
   path("logout", views.logout_view, name="logout"),



]

library/views.py
from django.shortcuts import  render  
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse,HttpResponseRedirect 
from django.urls import reverse
from .models import  User,  Book, Author,  Student,  BookInstance, LibraryStaff

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("library:login"))
    else:    
        return render(request, "library/index.html")


def form(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("library:login"))
    else:
       
        return render(request, "library/forms.html")

       

def books(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("library:login"))
    else:
        allBooks= Book.objects.all()
        return render(request, "library/books.html", {"allBooks":allBooks})

def add_books(request):
        # obtain data from the form
    if request.method == "POST":
        category= request.POST.get("addCat")
        title= request.POST.get("addTit")
        about_the_book= request.POST.get("book_theme")
        book_condition= request.POST.get("status")
        refId= request.POST.get("addRef")
        imageUrl= request.POST.get("addUrl")
        price= request.POST.get("addPrice")
        author= request.POST.get("addAut")
        copies= request.POST.get("addCopies")
        print(category,title,about_the_book,book_condition,refId,imageUrl,price,author,copies)

        addBooks= Book()
        addBooks.category= category
        addBooks.title= title
        addBooks.about_the_book= about_the_book
        addBooks.book_condition= book_condition
        addBooks.refId= refId
        addBooks.imageUrl= imageUrl
        addBooks.price= price
        addBooks.author= author
        addBooks.copies= copies
        addBooks.save()
        
        #add book
        return HttpResponse("book added successfully")





     
     
















def book_details(request, id):
        
        book_detail= Book.objects.get(id=id)
        return render(request, "library/book_details.html",{
             'book_detail':book_detail,
             })





def book_borrowed_view(request):
        borrowed_books= BookInstance.objects.all()
        return render(request, "library/book_borrowed.html",{'borrowed_books':borrowed_books})

def book_borrowed(request):
    if request.method == "POST":
        studentName= request.POST.get("student_name_1")
        student_refId= request.POST.get("student_id")
        category=request.POST.get("borCat")
        title= request.POST.get("borTit")
        author= request.POST.get("borAut")
        refId= request.POST.get("borRef")
        book_condition= request.POST.get("borCondition")
        dateBorrowed= request.POST.get("borDat")
        return_date= request.POST.get("retDat")
        status= request.POST.get("borStatus")

        borrowed_book= BookInstance()
        borrowed_book.studentName= studentName
        borrowed_book.student_refId= student_refId
        borrowed_book.category= category
        borrowed_book.title = title
        borrowed_book.author= author
        borrowed_book.refId= refId
        borrowed_book.book_condition= book_condition
        borrowed_book.dateBorrowed= dateBorrowed
        borrowed_book.return_date= return_date
        borrowed_book.status= status
        borrowed_book.save()

        #redirect to index page
        return HttpResponse("successfully borrowed")
    











    

def all_books(request):
    allBooks= Book.objects.all()
    return render(request, "library/all_books.html", {"allBooks":allBooks})




def author(request):
        authors= Author.objects.all()
        return render(request, "library/author.html", {"authors":authors})


def author_profile(request):
        author_profiles=Author.objects.all()
        return render(request, "library/author_profile.html", {"author_profiles":author_profiles})






def student(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("library:login"))
    else:
      
        studentNames= Student.objects.all()
        context= {
            'studentNames':studentNames
        }
        return render(request, "library/student.html", context) 


def add_student(request):
    if request.method == "POST":
        referenceId=request.POST.get('student_1')
        studentName=request.POST.get('student_2')
        phone_number=request.POST.get('student_3')
        parents=request.POST.get('student_4')
        residence=request.POST.get('student_5')
        
        studentProfile= Student()
        studentProfile.referenceId=referenceId
        studentProfile.studentName= studentName
        studentProfile.phone_number= phone_number
        studentProfile.parents= parents
        studentProfile.residence= residence

        studentProfile.save()
        return HttpResponse("REGISTERED")







         
          


     
          
     



  

  






def lib_staff(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("library:login"))
    else:
        library_staff= LibraryStaff.objects.all()
        return render(request, "library/lib_staff.html", {"library_staff":library_staff})  
    



 

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username= username, password= password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("library:index"))
        else:
            return render(request, "library/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "library/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("library:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure StudentId matches confirmation
        password = request.POST.get("password")
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "library/register.html", {
                "message": "password must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username,email, password)
            user.save()
        except IntegrityError:
            return render(request, "library/register.html", {
                "message": "username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("library:index"))
    else:
        return render(request, "library/register.html")

library/templates/library/all_books.html
{% extends "library/layout.html" %}
{% load static %}

    
{%  block content  %} 
<style>
    body{
        background-color:darkgrey;
    }
    .container{
        width:70%;
        height:auto;
        padding:10px;
        background-color:lightgrey;
    }
    thead{
        background-color:lightblue;
        color:white;
    }
    .table-container{
        height:400px;
        overflow-y:scroll;
    }
</style>
<div class="container">
        <h1>BOOK DATABSE</h1>
   
        <h2>{{allBooks.count}} book type collections.</h2>
        
    <div class="table-container">   
            <table class="table">
            <thead>
                <tr>
                    <td>CATEGORY</td>
                    <td>TITLE</td>
                    <td>CONDITION</td>
                    <td>ABOUT THE BOOK</td>
                    <td>REFID</td>
                    <td>PRICE</td>
                    <td>AUTHOR</td>
                    <td>COPIES</td>
                </tr>

            </thead>
            <tbody>
                {% for allBooks in allBooks %}
                    <tr>
                            <td>{{allBooks.category}}</td>
                            <td>{{allBooks.title}}</td>
                            <td>{{allBooks.book_condition}}</td>
                            <td>{{allBooks.about_the_book}}</td>
                            <td>{{allBooks.refId}}</td>
                            <td>{{allBooks.price}}</td>
                            <td>{{allBooks.author}}</td>
                            <td>{{allBooks.copies}}</td>
                            
                    </tr>
                {% endfor %}
            </tbody>
            </table></br></br>
        
        </div>
    </div>
        <div id="links">
            
            <a href="{% url 'library:book_borrowed_view'%}">BOOKS BORROWED</a></br>
            <a href="{% url 'library:author'%}">AUTHORS</a></br>
            
        </div>
    </div>  

    
    
        
{% endblock content %} 
      

library/templates/library/author.html
{% extends "library/layout.html" %}
{% load static %}

    
{%  block content  %}  
    <h1>AUTHORS<h1>
    <div>
    {% if authors %}
        <ol>
            {% for authors in authors %}
            <li>Name:<a href="{% url 'library:author_profile'%}">{{authors.first_name}}  {{authors.last_name }}</li>
                
                 
            {% endfor %}
        </ol>
    {% else %}
        <p style="font-size:18px"> Not found</p>  
    {% endif %} 
    </div>   
{% endblock content %}

library/templates/library/book_borrowed.html
{% extends "library/layout.html" %}
{% load static %}

{% block content %}
<style>
    body{
    background-color:rgba(87, 94, 87, 0.4);
    }
    h1, h2{
        text-align:center;
        color:indigo;
        text-shadow:2px 2px 2px lightgrey;
        margin-bottom:10px;
    }
    thead{
        background-color:lightblue;
        font-weight:bold;

    }
    
</style>
<h1>BORROWED BOOKS </h1></br></br>
<h2>{{borrowed_books.count}} books borrowed.</h2>
<div>
    {% if borrowed_books %}
    <div class="bkBorrowed">
        <ul>
            {% for  borrowed_books in  borrowed_books %}
            
           
            {% endfor%}   
        </ul>
    </div>
    {% else %}
        <p style="font-size:18px">Books not available</p>  
    {% endif %} 
</div>   


<div class="row" style="margin-top:20px;">
    <div class= "container" style="overflow-y-auto;height= 400px;margin-bottom:20px;">
        <table class= "table table-hover">
            <thead>
                <tr>
                    <td>STUDENT NAME</td>
                    <td>STUDENT REF/ID</td>
                    <td>CATEGORY</td>
                    <td>TITLE</td>
                    <td>BOOK REF/ID</td>
                    <td>BOOK CONDITION</td>
                    <td>DATE BORROWED</td>
                    <td>RETURN DATE</td>
                    <td>STATUS</td>
                </tr>
            </thead>
            <tbody>
                {% for borrowed_books in borrowed_books %}
                    <tr>
                            <td>{{borrowed_books.studentName}}</td>
                            <td>{{borrowed_books.student_refId}}</td>
                            <td>{{borrowed_books.category}}</td>
                            <td>{{borrowed_books.title}}</td>
                            <td>{{borrowed_books.refId}}</td>
                            <td>{{borrowed_books.book_condition}}</td>
                            <td>{{borrowed_books.dateBorrowed}}</td>
                            <td>{{borrowed_books.return_date}}</td>
                            <td>{{borrowed_books.status}}</td>

                    </tr>
                {% endfor %}
            </tbody>
           
        </table>
    </div>
</div>
</div>

{% endblock content %}

library/templates/library/books.html
{% extends "library/layout.html" %}
{% load static %}

    
{%  block content  %} 
<style>
    body{  
    background-color:rgba(226, 241, 14, 0.78);
    text-align:center;
    
    }
    li{
        list-style-type:none;
    }
    .bkImage li{
        display:inline;
    }
    #links a{
        font-size:20px;
        margin:15px;
    }



</style>
<div id="allBooks">
    <h4>{{allBooks.count}} book samples available.</h4>
    {% if allBooks %}
        <ul class="bkImage">
            {% for allBooks in allBooks %}
            <li><img src="{{allBooks.imageUrl}}"></li>
            <li><a href="{% url 'library:book_details_name' id=allBooks.id %}">{{allBooks.title }}<a/></li>   
            {% endfor %}   
        </ul>
    {% else %}
        <p style="font-size:10px">Books not available</p>  
    {% endif %} 
    
</div>   
     
    
    
    
  
<div id="links">
    
    <a href="{% url 'library:book_borrowed_view'%}">BOOKS BORROWED</a>
    <a href="{% url 'library:author'%}">AUTHORS</a>
    <a href="{% url 'library:all_books'%}">BOOKS DATABASE</a>
</div>
          
{% endblock content %} 
      

library/templates/library/forms.html
{% extends "library/layout.html" %}
{% load static %}




    
{%  block content  %}
<style>
  body{
     background-image: linear-gradient(to right, red, orange, yellow, green, rgb(179, 179, 201), indigo,violet);
  }

button{
  border-radius:5px;
  border:none;
  margin:10px;
}
td{
  color:white;
}
input{
  border-radius:5px;
  border:none;
}
#addCat{
  width:186px;
  padding:2px;
  border-radius:5px;
  border:none;
}
</style>

  
    <button data-page="register">Be a member</button>
    <button data-page="addBook">Add book</button>
    <button data-page="borrow_a_book">Borrow a book</button>
  
  
    
    
    <div id="register">
      <h4>Student/Readers Membership Registration</h4>
      <form class="d-flex" action="add_student" method="POST">
              {% csrf_token %}
              <table class="table" style="margin-top: 20px;">
                  <tr>
                      <td>ReferenceId:</td>
                      <td><input type="text" class="form_1" name="student_1" placeholder="ReferenceId" required></td>
                  </tr>
                  <tr>
                      <td >StudentName:</td>
                      <td><input type="text" class="form_2" name="student_2" placeholder="StudentName" required></td>
                  </tr>
                  <tr>
                      <td>PhoneNumber:</td>
                      <td><input type="text" class="form_3" name="student_3" placeholder="PhoneNumber" "required></td>
                  </tr>
                  <tr>
                      <td>Parents/Guarantor:</td>
                      <td><input type="text" class="form_4" name="student_4" placeholder="Parents/Guarantor" required></td>
                  </tr>
                  <tr>
                      <td>Residence:</td>
                      <td><input type="text" class="form_5" name="student_5" placeholder="Residence" required></td>
                  </tr>
                  <tr>
                      <td colspan="2"><button style="padding: 2px;background-color:lightblue;border-radius:5px" type="submit">save</button></td>
                  </tr>  
              </table>  
      </form>           
    
    </div>

  
  

     

  <div id="addBook">
    <h4>CONTRIBUTE A BOOK</h4>
    <form id="addBook1" action="/add_books" method="POST">
            {% csrf_token %}
            <table class="table" style="margin-top: 20px;">
                <tr>
                  <td>CATEGORY:</td>
                  <td>
                  <select id="addCat" name="addCat" required>
                  <option value="Religion">Religion</option>
                  <option value="Fiction">Fiction</option>
                  <option value="History">History</option>
                  <option value="Science">Science</option>
                  <option value="Mathematics">Mathematics</option>
                  <option value="Business">Business</option>.
                  <option value="Languages">Languages</option>
                  </select>

                  </td>
                </tr>
                
                <tr>
                  <td>BOOK TITLE:</td>      
                  <td><input type="text"  name="addTit" placeholder="title" required></td>
                </tr>
              
                <tr>
                  <td>ABOUT THE BOOK:</td>      
                  <td><input type="text"  name="book_theme" placeholder="description" required></td>
                </tr>

                <tr>
                  <td>BOOK CONDITION:</td>      
                  <td><input type="text"  name="status" placeholder="book_status" required></td>
                </tr>

                <tr>  
                  <td>REFID:</td>
                  <td><input type="text"  name="addRef" placeholder="ref" required></td>
                </tr> 

                <tr>    
                  <td>IMAGEURL:</td>
                  <td><input type="text"  name="addUrl" placeholder="imageUrl" required></td>
                </tr>


                <tr>
                  <td>PRICE:</td>     
                  <td><input type="number"  name="addPrice" placeholder="book_price" required></td>
                </tr>
              
                <tr>  
                  <td>AUTHOR:</td>     
                  <td><input type="text"  name="addAut" placeholder="author" required></td>
                </tr>
              
                <tr>  
                  <td>COPIES:</td>      
                  <td><input type="text"  name="addCopies" placeholder="book_copies" required></td>
                </tr>
                <tr>
                  <td><button type="submit">Add a book</button></td>
                </tr>
            </table class="table" style="margin-top: 20px;">
      </form>
</div>


<div id="borrow_a_book">
  <h4>BORROW A BOOK </h4>
  <form id="borrow_a_book1" action="book_borrowed" method="POST">
        {% csrf_token %}
        <table class="table" style="margin-top: 20px;">
            <tr>
              <td>STUDENT NAME:</td>   
              <td><input type="text" mx='30' max='50' name="student_name_1" placeholder="name" required></td>
            </tr>

            <tr>
              <td>STUDENT REF ID:</td>   
              <td><input type="text" mx='30' max='50' name="student_id" placeholder="studentID" required></td>
            </tr>
      
            <tr>
              <td>CATEGORY:         
              <td><input type="text" mx='30' max='50' name="borCat" placeholder="category" required></td>
            </tr>
      
          <tr>
              <td>TITLE:</td>      
              <td><input type="text" mx='30' max='50' name="borTit" placeholder="title" required></td>
          </tr>
          
          <tr>
              <td>AUTHOR:</td>     
              <td><input type="text" max='50' name="borAut" placeholder="author" required></td>
          </tr>
          
          <tr>
              <td>BOOK REF ID:</td>
              <td><input type="text" max='50' name="borRef" placeholder="ref" required></td>
          </tr>

              <td>BOOK CONDITION:</td> 
              <td><input type="text" max='50' name="borCondition" placeholder="condition" required></td>
          </tr>

          <tr>
            <td>DATE BORROWED:</td>      
            <td><input type="text" max='50' name="borDat" placeholder="date borrowed" required></td>
          </tr>

      
      
          <tr>
              <td>RETURN DATE:</td>      
              <td><input type="text" max='50' name="retDat" placeholder="return date" required></td>
          </tr>

          <tr>
              <td>STATUS:</td>      
              <td><input type="text" max='50' name="borStatus" placeholder="status" required></td>
          </tr>
          <tr>
            <td><button type="submit">Borrow a book</button></td>
          <tr>
      <table>
</form>
</div>

<script>
  function showPage(page) {
    document.querySelectorAll('div').forEach(div => {
        div.style.display ='none';
        })
    
        document.querySelector(`#${page}`).style.display= 'block';
      }
    
        document.addEventListener('DOMContentLoaded', function() {
            document.querySelectorAll('button').forEach(button => {
            button.onclick = function() {
                showPage(this.dataset.page);           
          }
        });
      });

</script>



         
{% endblock content %}

library/templates/library/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}LIBRARY{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'library/styles.css' %}" rel="stylesheet">
        <script src="main.js"></script>
        
    </head>
    <style>
        a:hover{
            background-color:white;
            color:rgba(0, 0, 255, 0.8);
            text-decoration:none;
            padding:5px;
        }
        body{
            background-color:rgba(0, 250, 20, 0.9)
        }
    </style>   
    
    <body>
    
        <h1 style="background-color:lightblue;text-shadow:3px 3px 3px blue;text-align:center">ACADEMIA LIBRARY</h1>
        <div  style="margin-left:15px">
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'library:index' %}">HOME</a>
            </li>
         
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'library:student'  %}">STUDENTS</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'library:books' %}">BOOKS</a>
            </li>
        

            <li class="nav-item">
                <a class="nav-link" href="{% url 'library:form' %}">FORMS</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'library:lib_staff' %}">LIBRARY STAFF</a>
            </li>

           

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'library:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'library:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'library:register' %}">Register</a>
                </li>
                
            {% endif %}
            
        </ul>
        <hr>
        {% block content %}
        {% endblock content %}
    
    </body>
</html>

library/templates/library/lib_staff.html
{% extends "library/layout.html" %}
{% load static %}

    
{%  block content  %} 
<style>
    body{
        background-image: radial-gradient(closest-side at  60% 55%, red, yellow,pink);
        ;
    }
</style>
   <body>
    <div id="libraryStaff">
    <h4>LIBRARY STAFF </h4>
    {% if library_staff %} 
          {% for library_staff in library_staff %}  
          <ul> 
              
              <li>  MANAGER: {{library_staff.manager}}</li>
              <li>  LIBRARIAN:{{library_staff.librarian}} </li>  
              <li>  ASSISTANT LIBRARIAN:{{library_staff.Assistant_librarian}}</li> 
              
          </ul> 
          {% endfor %}   
    {% else %}
    <p style="font-size:18px">Not available</p>  
    {% endif %}           
    
    </div> 
</body>
   
{% endblock content %}

library/templates/library/login.html
{% extends "library/layout.html" %}

{% block content %}
<style>
    body{
        background-color:rgba(0, 250, 20, 0.9);
        
    }
    .container{
        display:flex;
        flex-direction:column;
        align-items:center;
        background-color:rgba(255, 255, 255, 0.8);
    }
    .form-group input{
        border-radius:5px;
        border:none;
        width:250px;
        
</style>

<div class="container">
    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'library:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="username">
        </div>
       
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'library:register' %}">Register here.</a>
</div>
{% endblock content %}

library/templates/library/student.html
{% extends "library/layout.html" %}
{% load static %}

    
{%  block content  %} 
<style>
    body{  
    background-color:cyan;
    }
    .studentContainer{
        background-color:pink;
        width:60%;
        margin:50px 200px 50px 250px;
        padding:50px 100px 50px 100px;    
    }
    .studentTable{
        height: 200px;
        overflow-y: scroll;
}
button{
    margin:10px 30%;
    text-align:center;
    width:200px;
    height:30px;
    border-radius:5px;
    border:none;
    
    
}

button:hover{
    background-color:cyan;
    
       
}
a{
    text-decoration:none;
    
}



</style>



<div class="studentContainer">
    <h4 style="text-align:center">{{studentNames.count}} students subscribed.</h4>
        <div class="studentTable">
            <table>
                <thead>
                    <tr style="text-transform:uppercase;color:black;background-color:cyan;padding:7px;">
                        <td>referenceId</td>
                        <td>studentName</td>
                        <td>phone_number</td>
                        <td>parents</td>
                        <td>residence</td>
                    </tr>
                </thead>
                
                <tbody>
                    {% for studentNames in studentNames %}
                        <tr style="background-color:white;">
                                <td>{{studentNames.referenceId}}</td>
                                <td>{{studentNames.studentName}}</td>
                                <td>{{studentNames.phone_number}}</td>
                                <td>{{studentNames.parents}}</td>
                                <td>{{studentNames.residence}}</td>
                                

                        </tr>
                    {% endfor %}
                </tbody>
            </table> 

          </div>
          <button style="color:white"><a href="{% url 'library:form'%}">Register as a member</a></button>
          
</div>

    
{% endblock content %}